Server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_x_test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: vincent2017727
logging:
  level:
    com.baomidou: debug
    com.baomidou.mybatisplus: debug
    com.baomidou.dynamic: debug
    com.vincent.com.vincent.mybatixtest.*: debug
    org.mybatis: debug
    org.springframework.jdbc.core: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml